import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import Testimonials from "../components/Testimonials/Testimonials.jsx";
import dataVisualizationImg from "../assets/home-data-visualization.jpg";
import dataInsightsImg from "../assets/home-data-insights.jpg";
import diabetesImg from "../assets/diabetes.jpeg";
import predictiveAnalyticsImg from "../assets/home-predictive-analytics.jpg";

const features = [
  {
    title: "Data Insights",
    description:
      "Explore the clinical variables behind the model and understand the structure of the dataset used in this project.",
    image: dataInsightsImg,
    cta: "Learn More",
    to: "/data-info",
  },
  {
    title: "Predictive Analytics",
    description:
      "Enter patient measurements and receive a diabetes risk prediction generated by the Flask backend.",
    image: predictiveAnalyticsImg,
    cta: "Get Prediction",
    to: "/prediction",
  },
  {
    title: "Data Visualization",
    description:
      "Review clean visual summaries and signal views that make the dataset easier to interpret.",
    image: dataVisualizationImg,
    cta: "View Charts",
    to: "/visualization",
  },
];

const Home = () => {
  return (
    <div className="page-shell">
      <div className="page-container space-y-10">
        <motion.section
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="relative overflow-hidden rounded-[2rem]"
        >
          <div
            className="absolute inset-0 bg-cover bg-center"
            style={{ backgroundImage: `url(${diabetesImg})` }}
          />
          <div className="absolute inset-0 bg-[linear-gradient(110deg,rgba(19,38,63,0.92)_0%,rgba(19,38,63,0.82)_42%,rgba(19,38,63,0.45)_100%)]" />

          <div className="relative px-6 py-16 md:px-10 lg:px-14 lg:py-24">
            <div className="max-w-3xl text-white">
              <span className="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-1 text-sm font-medium text-cyan-100">
                Clinical Decision Support
              </span>
              <h1 className="mt-6 text-4xl font-bold tracking-tight md:text-5xl lg:text-6xl">
                Diabetes prediction with a cleaner, more usable workflow.
              </h1>
              <p className="mt-6 max-w-2xl text-base leading-8 text-slate-200 md:text-lg">
                VitalityNet brings model-backed prediction, dataset context, and visual
                summaries into one calm interface for early diabetes risk assessment.
              </p>
              <div className="mt-8 flex flex-wrap gap-4">
                <Link to="/prediction" className="primary-btn">
                  Start Prediction
                </Link>
                <Link
                  to="/data-info"
                  className="secondary-btn border-white/20 bg-white/10 text-white hover:bg-white/15"
                >
                  Explore Dataset
                </Link>
              </div>

              <div className="mt-10 flex flex-wrap gap-3 text-white/90">
                <HeroMeta value="8" label="Clinical fields used" />
                <HeroMeta value="3" label="Core project modules" />
                <HeroMeta value="24/7" label="Available to explore" />
              </div>
            </div>
          </div>
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, delay: 0.1 }}
          className="space-y-4"
        >
          <div className="max-w-3xl">
            <span className="eyebrow">Core Features</span>
            <h2 className="section-title mt-4">Everything follows one simple workflow.</h2>
            <p className="section-copy mt-4">
              Review the data, run a prediction, and inspect the visuals without jumping
              across mismatched screens.
            </p>
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            {features.map((feature, index) => (
              <motion.article
                key={feature.title}
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="surface-card overflow-hidden"
              >
                <img
                  src={feature.image}
                  alt={feature.title}
                  className="h-56 w-full object-cover"
                />
                <div className="space-y-4 p-6">
                  <h3 className="text-2xl font-semibold text-slate-900">{feature.title}</h3>
                  <p className="text-sm leading-7 text-slate-600 md:text-base">
                    {feature.description}
                  </p>
                  <Link to={feature.to} className="primary-btn">
                    {feature.cta}
                  </Link>
                </div>
              </motion.article>
            ))}
          </div>
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, delay: 0.15 }}
          className="surface-card px-6 py-8 md:px-8 md:py-10"
        >
          <Testimonials />
        </motion.section>
      </div>
    </div>
  );
};

const HeroMeta = ({ label, value }) => (
  <div className="rounded-full border border-white/15 bg-white/10 px-5 py-3 backdrop-blur-sm">
    <span className="text-lg font-semibold text-white">{value}</span>
    <span className="ml-2 text-sm text-slate-200">{label}</span>
  </div>
);

export default Home;
